{:eqdata=>
  {:description=>"",
   :should_include=>"true",
   :variables=>
    {:afbs=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:afbs,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :afbs2=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:afbs2,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ap=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ap,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :aplace=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:aplace,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ap2=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ap2,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :aspct=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:aspct,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :at=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:at,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :at2=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:at2,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :at3=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:at3,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :at4=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:at4,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :awidth=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:awidth,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :beans=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:beans,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :bentaxis=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:bentaxis,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :bentqprofile=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:bentqprofile,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :bentradius=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:bentradius,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :bplace=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:bplace,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :bsfrac=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:bsfrac,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :bwidth=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:bwidth,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :b0exp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:b0exp,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ceta=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ceta,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :cfbal=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cfbal,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :cfnress=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cfnress,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :cfnresso=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cfnresso,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :cocos_in=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cocos_in,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :cocos_out=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cocos_out,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :cplace=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cplace,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :cpress=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cpress,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :cpresso=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cpresso,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :cq0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cq0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :csspec=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:csspec,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :currt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:currt,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :cwidth=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cwidth,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :delta=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:delta,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :dlambda=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:dlambda,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :dplace=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:dplace,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :dpsi_ni=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:dpsi_ni,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :dpsi_ti=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:dpsi_ti,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :dwidth=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:dwidth,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :elong=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:elong,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :eplace=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:eplace,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :etaei=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:etaei,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ewidth=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ewidth,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :epslon=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:epslon,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :gamma=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:gamma,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :lambda0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:lambda0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :pangle=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:pangle,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :predge=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:predge,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :psiscl=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:psiscl,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :qspec=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:qspec,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :qplace=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:qplace,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :qwidth=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:qwidth,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :qvalneo=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:qvalneo,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rboxlen=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rboxlen,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rboxlft=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rboxlft,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rc=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rc,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :relax=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:relax,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rext=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rext,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rnu=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rnu,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rodabyrod0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rodabyrod0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rpeop=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rpeop,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rzion=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rzion,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rz0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rz0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rz0w=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rz0w,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :r0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:r0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :r0exp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:r0exp,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :r0w=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:r0w,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :scalne=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:scalne,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :scexp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:scexp,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :sd_vmin=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:sd_vmin,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :sd_vmax=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:sd_vmax,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :signb0xp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:signb0xp,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :signipxp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:signipxp,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :sgma=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:sgma,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :slimit=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:slimit,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :snumber=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:snumber,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :solpda=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:solpda,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :solpdb=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:solpdb,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :solpdc=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:solpdc,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :solpdd=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:solpdd,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :solpde=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:solpde,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :spitzer=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:spitzer,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :tensprof=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:tensprof,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :tensbnd=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:tensbnd,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :theta0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:theta0,
       :must_pass=>[{:test=>nil, :explanation=>nil}],
       :type=>nil},
     :treeitm=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:treeitm,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :triang=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:triang,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :triplt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:triplt,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :xi=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:xi,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :zboxlen=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:zboxlen,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :mdt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:mdt,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :msmax=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:msmax,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nanal=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nanal,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nbal=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nbal,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nblc0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nblc0,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nblopt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nblopt,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nbpsout=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nbpsout,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nbsexpq=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nbsexpq,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nbsfun=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nbsfun,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nbsopt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nbsopt,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nbstrp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nbstrp,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nchi=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nchi,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ncscal=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ncscal,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ndiagop=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ndiagop,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ndifps=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ndifps,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ndift=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ndift,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :negp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:negp,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :neonbqs=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:neonbqs,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :neqdsk=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:neqdsk,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ner=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ner,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nitmopt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nitmopt,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nitmrun=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nitmrun,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nitmshot=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nitmshot,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nfftopt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nfftopt,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nfunc=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nfunc,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nfunrho=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nfunrho,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nideal=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nideal,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ninmap=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ninmap,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ninsca=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ninsca,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nipr=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nipr,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :niso=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:niso,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nmesha=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nmesha,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nmeshb=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nmeshb,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nmeshc=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nmeshc,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nmeshd=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nmeshd,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nmeshe=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nmeshe,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nmgaus=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nmgaus,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nopt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nopt,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :noutxtor=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:noutxtor,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nplot=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nplot,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npoida=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npoida,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npoidb=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npoidb,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npoidc=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npoidc,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npoidd=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npoidd,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npoide=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npoide,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npopulations=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npopulations,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npoidq=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npoidq,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npp,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nppfun=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nppfun,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nppr=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nppr,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nprofz=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nprofz,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npropt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npropt,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nprpsi=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nprpsi,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npsi=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npsi,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nrbox=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nrbox,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nrbox_xtor=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nrbox_xtor,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nrfp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nrfp,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nrscal=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nrscal,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ns=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ns,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nsgaus=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nsgaus,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nsmooth=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nsmooth,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nsour=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nsour,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nsttp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nsttp,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nsurf=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nsurf,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nsym=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nsym,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nt,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ntcase=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ntcase,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ntgaus=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ntgaus,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ntest=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ntest,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ntmf0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ntmf0,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ntnova=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ntnova,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nturn=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nturn,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nv=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nv,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nvexp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nvexp,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nzbox=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nzbox,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nzbox_xtor=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nzbox_xtor,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :neqdxtpo=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:neqdxtpo,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nverbose=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nverbose,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :comments=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:comments,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String}}},
 :newrun=>
  {:description=>"",
   :should_include=>"true",
   :variables=>
    {:al0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:al0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :angle=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:angle,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :arrow=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:arrow,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :beta=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:beta,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :betap=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:betap,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :cpsrf=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:cpsrf,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :epscon=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:epscon,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :epsmac=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:epsmac,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :qiaxe=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:qiaxe,
       :must_pass=>[{:test=>nil, :explanation=>nil}],
       :type=>nil},
     :qsurf=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:qsurf,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :rext_new=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rext,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ritot=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ritot,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :tsurf=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:tsurf,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :wntore=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:wntore,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :wall=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:wall,
       :must_pass=>[{:test=>nil, :explanation=>nil}],
       :type=>nil},
     :rinor=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rinor,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :qcyl=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:qcyl,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :p0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:p0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :nal0auto=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nal0auto,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ner_new=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ner,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :negp_new=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:negp,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :itest=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:itest,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :meq=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:meq,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nchi_new=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nchi,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ndes=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ndes,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nfig=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nfig,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nitmax=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nitmax,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nprnt=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nprnt,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :npsi_new=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npsi,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nsave=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nsave,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nua1=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nua1,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nua2=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nua2,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nub1=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nub1,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nub2=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nub2,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nux=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nux,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nupl=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nupl,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nusg=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nusg,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nv_new=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nv,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nuwa=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nuwa,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nvac=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nvac,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nvit=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nvit,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nwall=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nwall,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nldiag=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nldiag,
       :must_pass=>[{:test=>nil, :explanation=>nil}],
       :type=>nil},
     :nleinq=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nleinq,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :nlgren=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nlgren,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :nlsym=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nlsym,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String}}}}
